# Generated by Django 2.1.4 on 2018-12-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image_field',
            field=models.ImageField(upload_to='myuploads'),
        ),
    ]
